### PR TITLE
Add sqlitebrowser

### PR DESCRIPTION
**Pull request by digitalsleuth**
In response to the request for SQLiteBrowser from [SIFT Issue #599](https://github.com/teamdfir/sift/issues/599), this PR will add SQLiteBrowser and the associated repo to accomplish the install.

### CODE REVIEW

**Comment by grrrrr** [comment]
I made a miscalculation in my ticket.  The 3rd party repo has the same versions that ship with Ubuntu, both being from 2021.  It could be simpler to use the version with Ubuntu instead of adding the repo and pgp keys

**Comment by digitalsleuth** [comment]
Hi @grrrrr , the version that packs with Ubuntu Focal by default is 3.11.2, while the linuxgndu repo actually provides 3.12.2. Once we move to support for Jammy, the version which comes with Jammy is 3.12.1, which is still a `minor` version ahead of the default in Focal. Going forward, once we support Jammy and deprecate Focal this might change, however since the installation impact is an extremely small footprint for a newer version, I think it is worth it to keep the repo.

Thank you for your feedback, and we do appreciate you coming up with another approach.

Cheers!

**Comment by ekristen** [comment]
@digitalsleuth can you update the package names to be `sift-package-<package-name>` and then add the package name to the `name` variable. This will prevent collisions if remnux has the same package or we pull in another state that uses that name.

**Comment by digitalsleuth** [comment]
Sure thing! Working on it now.

**Comment by digitalsleuth** [comment]
I'll do this for all packages and re-issue a new PR with all of them updated.

**Comment by digitalsleuth** [comment]
This is done now, just testing. Once testing is finished, I'll submit that PR (for just the fixed names, not sqlitebrowser). Then once that's merged I'll submit the sqlitebrowser PR again.

**Pull request closed without merging**
