### PR TITLE
4n6 scripts

### PR DESCRIPTION
**Pull request by digitalsleuth**
Updates for the 4n6 scripts state.

### CODE REVIEW

**Comment by ekristen** [comment]
@digitalsleuth can you update this to just be the 4n6 scripts and make it work with the latest `master` branch, as Jammy support has now been merged.

**Comment by digitalsleuth** [comment]
Indeed, will get to it this afternoon.

**Comment by digitalsleuth** [comment]
Not sure why the other states got pulled into it.. interesting..

**Comment by ekristen** [comment]
Superseded by #83

**Pull request closed without merging**
