### PR TITLE
Full python re-org, splitting 2 from 3

### PR DESCRIPTION
**Pull request by digitalsleuth**
This pull is intended to split python2 packages (python-packages) from python3 packages (python3-packages), and fix any underlying python issues as a result of the upgrade to saltstack, deprecation of python2, and future support for python3 and Ubuntu Focal.
Key points to note:
- volatility has been fixed and should now be fully functional. This includes updating the mimikatz plugin [sift/issues/281](https://github.com/teamdfir/sift/issues/281) and its requirements (namely, fixing the construct error)
- Any python tools which now support python3 have been ported to python3
- Any python3-compatible components which were installed as dependencies to python2 scripts (ie: python-registry) have been left as python2 installs, however added as python3 installs as well until the originating tool is either no longer necessary or has been updated to python3
- appcompatcache has been fixed
- Ubuntu 18 and 20 support has been confirmed for all packages (python-based packages at least)
- pyhindsight has been added. It was a state file but not called by the init. Support for python3 confirmed and tested.
- All standalone scripts which have had the `/usr/bin/env python` shebang have been changed to `/usr/bin/env python2` for current and future support for python3
- python2-pip state has been updated to only install get-pip once, and confirm if pip already exists, to prevent multiple installs. 
- Added poster as a requirement for virustotal-submit (Didier Stevens script)
- corrected the python-wxgtk3.sls
- Added python2-dev package for Ubuntu 20.04 compatibility for python2 packages (namely m2crypto and distorm3)

### CODE REVIEW

**Comment by ekristen** [comment]
Thanks @digitalsleuth --- you beat me to it. 

Testing and validating now!

**Comment by ekristen** [comment]
Looks like volatility is still not working properly with the plugins but a lot of the changes are great. I'll continue to review.

**Comment by digitalsleuth** [comment]
Did you run it in a clean environment? I ran it in both 18 and 20 dockers, and 18 and 20 VM's and all of them seem to work fine, and tested then with NIST standard memory dumps.

**Comment by digitalsleuth** [comment]
Can you check and see if you have pycrypto and/or pycryptodomex on your system?

**Comment by digitalsleuth** [comment]
The only reason that error would come up is if either pycrypto hadn't been installed (yet, perhaps the testing is still ongoing?) or pycrypto got removed somehow. As it is a requirement for volatility which installs by default, the easiest option to solve this is to create a new state which installs pycrypto. I'll do one up now. It should at least provide a failsafe.

**Comment by ekristen** [comment]
Super clean env, we'll definitely want to get it in as dep. Happy to accept your commit. The only thing I think I might tweak is putting this in a virtualenv because that's the core diff between what I had and your work.

**Comment by digitalsleuth** [comment]
Sounds good. That can be done. Gimme a few more minutes.

**Comment by ekristen** [comment]
No worries. Appreciate the support.

**Comment by digitalsleuth** [comment]
Forgot to remove the virtualenv state before this pull. Removed it above.

**Comment by ekristen** [comment]
Nice work @digitalsleuth. Thanks for the contribution. I'm reviewing now, if I run into any issues, I'll let you know.

**Pull request merged**
